MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen SPIELBRG
RegisterCurrent SPIELBRG\OBJ
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\SPIELBRG
FilerCurrent e:\CHARYBDS\MYTHOS95\SPIELBRG\MM.MMD
