MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen BOZO
RegisterOpen BOZO\INC
RegisterOpen BOZO\OBJ
RegisterOpen BOZO\TEST
RegisterOpen BOZO\TEST\OBJ
RegisterCurrent BOZO\README.TXT
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\BOZO
FilerCurrent e:\CHARYBDS\MYTHOS95\BOZO\BOZO.RTF
