MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterCurrent MYTHOS95
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\UTIL
FilerOpen e:\CHARYBDS\MYTHOS95\UTIL\OBJ
FilerCurrent e:\CHARYBDS\MYTHOS95\UTIL\README.TXT
