MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen MYTHOS95
RegisterOpen MYTHOS95\DOC
RegisterOpen MYTHOS95\UTIL
RegisterOpen MYTHOS95\UTIL\OBJ
RegisterCurrent MYTHOS95\UTIL\MYTHUG.SAM
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\UTIL
FilerOpen e:\CHARYBDS\MYTHOS95\UTIL\OBJ
FilerCurrent e:\CHARYBDS\MYTHOS95\UTIL\README.TXT
