//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
// MaxC -- Event and Trigger Definition System                              ³
// (C) 1994-1999 by D. Higdon, T. Little, and C. Walbourn                   ³
//                                                                          ³
// Event Constants header file for C++                                      ³
//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
#define left MaxEvent (0)
#define fire MaxEvent (1)
#define hello MaxEvent (2)
#define right MaxEvent (3)
#define up MaxEvent (4)
#define down MaxEvent (5)
#define mmove MaxEvent (6)
#define done MaxEvent (7)
#define targselect MaxEvent (8)
#define wepselect MaxEvent (9)
#define otherselect MaxEvent (10)
// EOF
