MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen IVORY
RegisterOpen IVORY\INC
RegisterOpen IVORY\OBJ
RegisterCurrent IVORY\INC\IVORY.HPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\IVORY
FilerCurrent e:\CHARYBDS\MYTHOS95\IVORY\IVMFC.C
