MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen IVORY
RegisterOpen IVORY\INC
RegisterOpen IVORY\OBJ
RegisterOpen IVORY\TEST
RegisterOpen IVORY\TEST\OBJ
RegisterCurrent IVORY\IVARENA.C
FilerOpen e:
FilerCurrent e:
