MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen GUTENBRG
RegisterOpen GUTENBRG\UTIL
RegisterOpen GUTENBRG\UTIL\OBJ
RegisterCurrent GUTENBRG\UTIL\GSTRING.H
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG\UTIL
FilerCurrent e:\CHARYBDS\MYTHOS95\GUTENBRG\UTIL\GFONT.L
