/*ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
 * Gutenberg -- Font and external string support                            ³
 * (C) 1995 by Charybdis Enterprises, Inc.  All Rights Reserved.            ³
 *                                                                          ³
 * String identifier header file for C/C++                                  ³
 *ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
 */

/* Identifiers for table: MyTable */
#define MYTHOS_NAME                                   1
#define COMPANY_NAME                                  34
#define GBERG_NAME                                    35

/* EOF */
