//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
// Gutenberg -- Font and external string support                            ³
// (C) 1995, 1996 by Charybdis Enterprises, Inc.  All Rights Reserved.            ³
//                                                                          ³
// String identifier header file for C++                                    ³
//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ

// Identifiers for table: MyTable
const unsigned long MYTHOS_NAME                                   = 1;
const unsigned long COMPANY_NAME                                  = 34;
const unsigned long GBERG_NAME                                    = 35;

// EOF
