MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen ESCHER
RegisterOpen ESCHER\EXPORT
RegisterCurrent ESCHER\EXPORT\VNGCOLOR.CPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\EXPORT
FilerCurrent e:\CHARYBDS\MYTHOS95\ESCHER\EXPORT\MK.BAT
