MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen ESCHER
RegisterOpen ESCHER\EXPORT
RegisterOpen ESCHER\EXPORT\INC
RegisterOpen ESCHER\EXPORT\IPAS
RegisterOpen ESCHER\EXPORT\LIB
RegisterOpen ESCHER\EXPORT\OBJ
RegisterOpen ESCHER\INC
RegisterCurrent ESCHER\EXPORT\SUPPORT.C
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\EXPORT
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\EXPORT\INC
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\EXPORT\IPAS
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\EXPORT\LIB
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\EXPORT\OBJ
FilerCurrent e:\CHARYBDS\MYTHOS95\ESCHER\EXPORT\MK.BAT
