MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen TURNER
RegisterCurrent TURNER\INC
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\TURNER
FilerOpen e:\CHARYBDS\MYTHOS95\TURNER\INC
FilerOpen e:\CHARYBDS\MYTHOS95\TURNER\OBJ
FilerCurrent e:\CHARYBDS\MYTHOS95\TURNER\TURNER.CPP
