MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen GAMEFR~1
RegisterOpen GAMEFR~1\INC
RegisterOpen GAMEFR~1\OBJ
RegisterCurrent GAMEFR~1\README.TXT
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\GAMEFR~1
FilerCurrent e:\CHARYBDS\MYTHOS95\GAMEFR~1\LLANDER.CIF
