MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen ESCHER
RegisterOpen ESCHER\EDIT
RegisterCurrent ESCHER\EDIT\ESHTVIEW.CPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\EDIT
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\EDIT\RES
FilerCurrent e:\CHARYBDS\MYTHOS95\ESCHER\EDIT\README.TXT
