//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by eshtedit.rc
//
#define ID_CREATE_FROM_COLOR            3
#define ID_MATCH_ALL_CLRS               3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ESCHERTYPE                  129
#define IDD_TERRPROP_GEN                132
#define IDD_TERRPROP_MISC               133
#define IDD_PROGRESS                    135
#define IDD_EXPORTSTAT                  136
#define IDD_SURFPROP_GEN                138
#define IDD_CAMPROP_GEN                 140
#define IDD_TXTPROP_GEN                 141
#define IDD_CAMPROP_MISC                143
#define IDD_TXTVIEW                     145
#define IDD_CAMPROP_LOD                 146
#define IDD_LGTPROP_GEN                 147
#define IDD_DEMIMPORT                   150
#define IDD_LGTPROP_EXTRA               151
#define IDD_TERRPROP_HGTCLR             152
#define IDD_COLORSELECT                 153
#define IDD_CLRPROP_GEN                 154
#define IDD_TXTCREATE_NEW               155
#define IDD_CLRCREATE_NEWTXT            156
#define IDD_TXTCREATE_ASK               157
#define IDD_SHADEREVIEW                 158
#define IDD_DEMPROGRESS                 159
#define IDD_TERRPROP_HTBL               160
#define IDD_TOOL_HEIGHT                 161
#define IDD_TOOL_RANDOM                 162
#define IDD_CAMPROP_EX                  163
#define IDD_TXTPROP_SFLAGS              164
#define IDD_TOOL_ANGLE                  165
#define IDD_LOCATE                      166
#define IDD_SETBASEELV                  167
#define IDB_ABOUT                       168
#define IDB_LOGO                        169
#define IDC_TPROP_WIDTH                 1000
#define IDC_TPROP_DEPTH                 1001
#define IDC_LPROP_TYPE                  1002
#define IDC_TPROP_SCALE                 1004
#define IDC_LPROP_INTENSITY             1004
#define IDC_EST_HDR                     1005
#define IDC_LPROP_XI                    1005
#define IDC_TPROP_NAME                  1006
#define IDC_EST_HGTS                    1006
#define IDC_LPROP_YJ                    1006
#define IDC_EST_SURF                    1007
#define IDC_LPROP_ZK                    1007
#define IDC_TPROP_DESC                  1008
#define IDC_EST_NRML                    1008
#define IDC_TPROP_AUTH                  1009
#define IDC_EST_TXTS                    1009
#define IDC_LPROP_ATTEN                 1009
#define IDC_TPROP_COPY                  1010
#define IDC_TPROP_SURFRATIO             1010
#define IDC_SPROP_XLOC                  1012
#define IDC_SPROP_DLOC                  1013
#define IDC_SPROP_COLR                  1015
#define IDC_SPROP_FLIPU                 1016
#define IDC_SPROP_FLIPV                 1017
#define IDC_SPROP_INDISTXT              1018
#define IDC_SPROP_CBIT4                 1019
#define IDC_SPROP_HIDDEN                1020
#define IDC_SPROP_WATER                 1021
#define IDC_SPROP_HIGHONLY              1021
#define IDC_CPROP_XPOS                  1022
#define IDC_SPROP_TILE                  1022
#define IDC_CPROP_BCOLR                 1023
#define IDC_SPROP_NOTILE                1023
#define IDC_CPROP_YPOS                  1024
#define IDC_TXPRP_NAME                  1024
#define IDC_SPROP_CBIT11                1024
#define IDC_SPROP_FIRE                  1025
#define IDC_CPROP_ZPOS                  1025
#define IDC_SPROP_CBIT12                1025
#define IDC_SPROP_SMOKE                 1026
#define IDC_CPROP_YON                   1026
#define IDC_TXTPRP_FILE                 1026
#define IDC_SPROP_APP0                  1026
#define IDC_CPROP_HITHER                1027
#define IDC_TXTPRP_BROWSE               1027
#define IDC_SPROP_APP1                  1027
#define IDC_CPROP_FOV                   1028
#define IDC_SPROP_TXT                   1028
#define IDC_CPROP_SCALEF                1028
#define IDC_TXTPRP_VIEW                 1028
#define IDC_TXTPRP_COLR                 1029
#define IDC_CPROP_HOVER                 1029
#define IDC_SPROP_APP2                  1029
#define IDC_ABOUT_VERSION               1030
#define IDC_TXTPRP_RESETUSAGE           1030
#define IDC_CPROP_ITOP                  1030
#define IDC_SPROP_APP3                  1030
#define IDC_CPROP_JTOP                  1031
#define IDC_TXTPRP_MAKENEW              1031
#define IDC_TXPROP_APP3                 1031
#define IDC_CSURF_PROG                  1032
#define IDC_CPROP_KTOP                  1032
#define IDC_TPROP_ORGX                  1033
#define IDC_CPROP_IDIR                  1033
#define IDC_TPROP_ORGY                  1034
#define IDC_CPROP_JDIR                  1034
#define IDC_TPROP_ORGZ                  1035
#define IDC_CPROP_KDIR                  1035
#define IDC_TPROP_AUTOORG               1036
#define IDC_TXPRP_TILE                  1037
#define IDC_TXPRP_FLIPU                 1038
#define IDC_TXPRP_FLIPV                 1039
#define IDC_TVIEW_WIDTH                 1041
#define IDC_TVIEW_HEIGHT                1042
#define IDC_BITMAP                      1045
#define IDC_LPROP_INNER                 1047
#define IDC_LOD                         1048
#define IDC_LPROP_OUTER                 1048
#define IDC_CPROP_HCOLR                 1048
#define IDC_CPROP_MED                   1049
#define IDC_CPROP_BMBACK                1049
#define IDC_CPROP_LOW                   1050
#define IDC_LPROP_HOTSPOT               1050
#define IDC_LPROP_FALLOFF               1051
#define IDC_CPROP_BITMAP                1051
#define IDC_CPROP_HAZE                  1052
#define IDC_TPROP_BLUE                  1054
#define IDC_CPROP_LEVEL                 1054
#define IDC_TPROP_LBLUE                 1055
#define IDC_CPROP_BLEVEL                1055
#define IDC_TPROP_WHITE                 1056
#define IDC_CPROP_SLEVEL                1056
#define IDC_CPROP_BPERC                 1057
#define IDC_TPROP_GREEN                 1061
#define IDC_TPROP_LGREEN                1062
#define IDC_TPROP_YELLOW                1063
#define IDC_TPROP_LORANGE               1064
#define IDC_CLRPRP_NAME                 1064
#define IDC_TPROP_ORANGE                1065
#define IDC_TPROP_LBROWN                1066
#define IDC_BITMAP2                     1066
#define IDC_TPROP_BROWN                 1067
#define IDC_TPROP_RED                   1068
#define IDC_SAVECLR                     1069
#define IDC_SAVECLR_SIZELIST            1071
#define ID_CREATE_FROM_FILE             1073
#define IDC_TVIEW_LOADBKTXT             1075
#define IDC_TVIEW_SAVEAS                1076
#define IDC_DEM_STD                     1078
#define IDC_DEM_UNIFORM                 1079
#define IDC_DEM_AVERAGE                 1080
#define IDC_DEM_AVGMAXD                 1081
#define IDC_DPRG_BAR                    1082
#define IDC_DPRG_FNAME                  1083
#define IDC_DPRG_NAME                   1084
#define IDC_DPRG_COMMENT                1085
#define IDC_DPRG_QUALITY                1087
#define IDC_DPRG_GUNITS                 1088
#define IDC_DPRG_EUNITS                 1089
#define IDC_DPRG_PROWS                  1090
#define IDC_DPRG_PCOLS                  1091
#define IDC_DPRG_AXISX                  1092
#define IDC_STATUS                      1093
#define IDC_DPRG_AXISZ                  1094
#define IDC_DEM_LNG_DEGREES             1095
#define IDC_DPRG_AXISY                  1095
#define IDC_DEM_LNG_MINUTES             1096
#define IDC_DEM_LNG_SECONDS             1097
#define IDC_DEM_LAT_DEGREES             1098
#define IDC_DEM_LAT_MINUTES             1099
#define IDC_DEM_LAT_SECONDS             1100
#define IDC_LNG_WEST                    1101
#define IDC_LNG_EAST                    1102
#define IDC_TROP_HGTS                   1105
#define IDC_LAT_NORTH                   1109
#define IDC_LAT_SOUTH                   1110
#define IDC_DEM_NORMALIZE               1111
#define IDC_TOOL_TC0                    1112
#define IDC_TOOL_TC1                    1114
#define IDC_TOOL_HEIGHT1                1115
#define IDC_TOOL_TC2                    1116
#define IDC_TOOL_HEIGHT2                1117
#define IDC_TOOL_TC3                    1118
#define IDC_TOOL_HEIGHT3                1119
#define IDC_TOOL_ALL                    1120
#define IDC_TOOL_SELECTED               1121
#define IDC_TOOL_HEIGHT0                1122
#define IDC_TOOL_TC4                    1123
#define IDC_TOOL_HEIGHT4                1124
#define IDC_TOOL_TC5                    1125
#define IDC_TOOL_HEIGHT5                1126
#define IDC_TOOL_TC6                    1127
#define IDC_TOOL_TC7                    1128
#define IDC_TOOL_HEIGHT6                1129
#define IDC_TOOL_HEIGHT7                1130
#define IDC_TOOL_RANGE0                 1131
#define IDC_TOOL_HEIGHT_STOP            1131
#define IDC_TOOL_RANGE1                 1132
#define IDC_TOOL_RANGE2                 1133
#define IDC_TOOL_RANGE3                 1134
#define IDC_TOOL_RANGE4                 1135
#define IDC_TOOL_RANGE5                 1136
#define IDC_TOOL_RANGE6                 1137
#define IDC_TOOL_RANGE7                 1138
#define IDC_TXPROP_NOTILE               1139
#define IDC_TXPROP_HIGHONLY             1140
#define IDC_TXPROP_APP0                 1141
#define IDC_TXPROP_APP1                 1142
#define IDC_TXPROP_APP2                 1143
#define IDC_CLRPRP_APP0                 1144
#define IDC_CLRPRP_APP1                 1145
#define IDC_CLRPRP_APP2                 1146
#define IDC_CLRPRP_APP3                 1147
#define IDC_CLRPRP_HIGHONLY             1148
#define IDC_CLRPRP_RESETUSAGE           1149
#define IDC_TOOL_PRESERVE               1150
#define IDC_TOOL_ANGLE_STOP             1151
#define IDC_TOOL_ANGLE0                 1152
#define IDC_TOOL_ANGLE1                 1153
#define IDC_TOOL_ANGLE2                 1154
#define IDC_TOOL_ANGLE3                 1155
#define IDC_TOOL_ANGLE4                 1156
#define IDC_TOOL_ANGLE5                 1157
#define IDC_TOOL_ANGLE6                 1158
#define IDC_TOOL_ANGLE7                 1159
#define IDC_TOOL_ELVLOW                 1160
#define IDC_TOOL_ELVCUTOFF              1161
#define IDC_TOOL_ELVHIGH                1162
#define IDC_LOCATE_FILE                 1162
#define IDC_LOCATE_BROWSE               1163
#define IDC_SETBASE_ELV                 1164
#define IDC_SETBASE_MIN                 1165
#define IDC_SETBASE_MAX                 1166
#define ID_FILE_EXPORT                  32787
#define ID_VIEW_ZOOM                    32790
#define ID_TERR_IMPORT                  32792
#define ID_TERR_PROP                    32793
#define ID_EDIT_PROP                    32794
#define ID_TXT_DEFINE                   32795
#define ID_TXT_SETPALETTE               32797
#define ID_TXT_PALETTE                  32798
#define ID_SURF_IMPORT                  32799
#define ID_SURF_PALETTE                 32800
#define ID_SURF_EDITTXT                 32803
#define ID_SURF_DEFINETXT               32804
#define ID_SURF_DELETETXT               32806
#define ID_VIEW_RENDER                  32808
#define ID_VIEW_REFRESH                 32809
#define ID_VIEW_ZOOM_NORM               32810
#define ID_VIEW_RND_SPECULAR            32816
#define ID_VIEW_RND_DOTS                32819
#define ID_VIEW_RND_WIREFRAME           32820
#define ID_VIEW_RND_FLAT                32821
#define ID_VIEW_RND_SMOOTH              32822
#define ID_VIEW_RND_BACKFACE            32824
#define ID_VIEW_RND_TEXTURES            32825
#define ID_VIEW_RND_SOLID               32826
#define ID_VIEW_RND_PERSPECTIVE         32827
#define ID_VIEW_ROTXY                   32828
#define ID_VIEW_MOVEXY                  32829
#define ID_VIEW_ROTMOVEZ                32831
#define ID_LGT_ADJUSTXY                 32833
#define ID_LGT_ABRIGHT                  32835
#define ID_VIEW_ZOOM_LARGE              32836
#define ID_VIEW_ZOOM_MED                32837
#define ID_VIEW_ZOOM_XLARGE             32838
#define ID_VIEW_PROP                    32840
#define ID_VIEW_ZOOM_MEGA               32842
#define ID_APP_HELP                     32843
#define ID_SURF_LOADTXT                 32844
#define ID_SURF_SAVETXT                 32845
#define ID_VIEW_HOVER                   32848
#define ID_LGT_PROP                     32849
#define ID_VIEW_SHOW_COLORS             32850
#define ID_VIEW_SHOW_SHADED             32851
#define ID_VIEW_SHOW_TXTONLY            32852
#define ID_VIEW_SHOW_HGT                32853
#define ID_SURF_DEFCLR                  32854
#define ID_SURF_EDITCLR                 32855
#define ID_SURF_DELETECLR               32856
#define ID_EDIT_FLIPH                   32857
#define ID_EDIT_FLIPV                   32858
#define ID_EDIT_ROT90                   32859
#define ID_EDIT_ROTN90                  32861
#define ID_EDIT_ASSIGN_HEIGHT           32863
#define ID_EDIT_ASSIGN_ROLL             32864
#define ID_VIEW_SHOW_APP                32865
#define ID_SURF_LOADCLR                 32866
#define ID_SURF_SAVECLR                 32867
#define ID_EDIT_ASSIGN_ANGLE            32868
#define ID_TERR_SETBASE                 32870
#define ID_SURF_REMTXT                  32871
#define ID_STATIC                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         32872
#define _APS_NEXT_CONTROL_VALUE         1166
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
