MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen SIMGINE
RegisterCurrent SIMGINE\SIMEQUIP.CPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\SIMGINE
FilerCurrent e:\CHARYBDS\MYTHOS95\SIMGINE\SIMSD3D.CPP
