MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen ESCHER
RegisterCurrent ESCHER\ESEXTSPH.CPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER
FilerCurrent e:\CHARYBDS\MYTHOS95\ESCHER\ESPCH.CPP
