MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen ESCHER
RegisterOpen ESCHER\EDIT
RegisterOpen ESCHER\EDIT\RES
RegisterOpen ESCHER\EXPORT
RegisterOpen ESCHER\INC
RegisterOpen ESCHER\OBJ
RegisterOpen ESCHER\TEST
RegisterOpen ESCHER\TEST\OBJ
RegisterOpen ESCHER\UTIL
RegisterOpen ESCHER\UTIL\OBJ
RegisterCurrent ESCHER\README.TXT
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER
FilerCurrent e:\CHARYBDS\MYTHOS95\ESCHER\ESCHER.RTF
