MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen FELIX
RegisterOpen FELIX\INC
RegisterOpen FELIX\OBJ
RegisterOpen FELIX\TEST
RegisterOpen FELIX\TEST\OBJ
RegisterCurrent FELIX\FLX16OPS.ASM
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\FELIX
FilerOpen e:\CHARYBDS\MYTHOS95\FELIX\INC
FilerOpen e:\CHARYBDS\MYTHOS95\FELIX\OBJ
FilerOpen e:\CHARYBDS\MYTHOS95\FELIX\TEST
FilerOpen e:\CHARYBDS\MYTHOS95\FELIX\TEST\OBJ
FilerCurrent e:\CHARYBDS\MYTHOS95\FLEX.ZIP
