MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen FELIX
RegisterCurrent FELIX\INC
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\FELIX
FilerCurrent e:\CHARYBDS\MYTHOS95\FELIX\FLXRAND.ASM
