MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen SYSTEM
RegisterCurrent SYSTEM\MYTMMX.ASM
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\SYSTEM
FilerCurrent e:\CHARYBDS\MYTHOS95\SYSTEM\MYTATEXT.C
