MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen SYSTEM
RegisterCurrent SYSTEM\INC
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\SYSTEM
FilerCurrent e:\CHARYBDS\MYTHOS95\SYSTEM\TEST
