MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen SYSTEM
RegisterOpen SYSTEM\INC
RegisterOpen SYSTEM\OBJ
RegisterOpen SYSTEM\TEST
RegisterOpen SYSTEM\TEST\OBJ
RegisterCurrent SYSTEM\MYTATEXT.C
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\SYSTEM
FilerCurrent e:\CHARYBDS\MYTHOS95\SYSTEM\MM.MMD
