MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen BACH
RegisterOpen BACH\INC
RegisterOpen BACH\OBJ
RegisterCurrent BACH\INC\BACHDIGI.HPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\BACH
FilerOpen e:\CHARYBDS\MYTHOS95\BACH\INC
FilerCurrent e:\CHARYBDS\MYTHOS95\BACH\INC\BACHWSEQ.HPP
