MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen BACH
RegisterCurrent BACH\BACHSWAV.CPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\BACH
FilerOpen e:\CHARYBDS\MYTHOS95\BACH\TEST
FilerCurrent e:\CHARYBDS\MYTHOS95\BACH\TEST\RESOURCE.RC
