MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen MYTHOS95
RegisterOpen MYTHOS95\EXAMPLES
RegisterOpen MYTHOS95\EXAMPLES\LLANDER
RegisterCurrent MYTHOS95\EXAMPLES\LLANDER\LLEVT.CEL
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\EXAMPLES
FilerOpen e:\CHARYBDS\MYTHOS95\EXAMPLES\LLANDER
FilerCurrent e:\CHARYBDS\MYTHOS95\EXAMPLES\LLANDER\LLANDER.CIF
