//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Paltool.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PTOOLTYPE                   129
#define IDD_PROGRESS                    130
#define IDD_PALETTE                     131
#define IDD_PROPA                       132
#define IDD_PROPB                       133
#define IDD_PROPC                       134
#define IDC_PROGRESSBAR                 1000
#define IDC_PROP_NAME                   1006
#define IDC_PAL_RED                     1007
#define IDC_PROP_DESC                   1008
#define IDC_PAL_GREEN                   1008
#define IDC_PROP_AUTH                   1009
#define IDC_PAL_BLUE                    1009
#define IDC_PROP_MIDPOINT               1009
#define IDC_PROP_COPY                   1010
#define IDC_PROP_SHDLVLS                1010
#define IDC_PAL_INDEX                   1012
#define IDC_PAL_SRED                    1013
#define IDC_PAL_SGREEN                  1014
#define IDC_PAL_SBLUE                   1015
#define IDC_COLOR                       1016
#define IDC_PROP_8BIT                   1017
#define IDC_PROP_15BIT                  1018
#define IDC_PROP_16BIT                  1019
#define IDC_PROP_24BIT                  1020
#define IDC_ABOUT_VERSION               1030
#define IDM_OPTIONS_LINEAR              32774
#define IDM_OPTIONS_BEZIER              32775
#define IDM_FILE_IMPORT                 32777
#define IDM_OPTIONS_QUADRATIC           32779
#define ID_EDIT_PROP                    32783
#define ID_EDIT_NEW_EMPTY               32786
#define ID_EDIT_NEW_GEN                 32787
#define ID_EDIT_NEW_ORIGGEN             32788
#define ID_EDIT_NEW_GREYSCALE           32789
#define ID_EDIT_NEW_332                 32790
#define ID_EDIT_NEW_RGBG                32791
#define ID_EDIT_PALETTE                 32792
#define ID_EDIT_NEW_SPC1                32793
#define ID_VIEW_REFRESH                 32794
#define ID_APP_HELP                     32796

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32797
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
