//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PalTool.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PTOOLTYPE                   129
#define IDC_SHADESCROLL                 130
#define IDD_PROGRESS                    130
#define IDC_HAZESCROLL                  131
#define IDC_PROGRESSBAR                 1000
#define IDM_LINEAR                      32771
#define IDM_BEZIER                      32772
#define IDM_QUADRATIC                   32773
#define IDM_OPTIONS_LINEAR              32774
#define IDM_OPTIONS_BEZIER              32775
#define IDM_FILE_IMPORT                 32777
#define IDM_OPTIONS_QUADRATIC           32779
#define IDM_FILE_EXPORT                 32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
