MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen XFILE
RegisterOpen XFILE\TEST
RegisterCurrent XFILE\TEST\MK.BAT
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\XFILE
FilerOpen e:\CHARYBDS\MYTHOS95\XFILE\TEST
FilerCurrent e:\CHARYBDS\MYTHOS95\XFILE\TEST\MK.BAT
