//อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
//                                         . .
//                                       , h $ F
//                                       ?,$,$,F
//                                       `$$$$$P  ,
//                                        ?$$$$L,c'
//                                         $$$$$"'
//                                        c$$P"                              
//;;,                                  .z$$$F                                
//!'',ccc                            ,c$$$P"                                 
// ,$$$$$".                        zJ$$$$"                        .z..       
//> $".,,c,.                     c$$$$$P'                        ,$$$$$c,.   
// z$$,.,$$$F                   $$$$$$P                          J$$$$PP$$$hc
//z$$$$$$$$$=                  "??$$$"                           <$$$$$ $$P".
//$$$$$$$$$,ccc             zJ$$$$$P'                            `?$$$$c " ??
//$$$$$$$$$$??"         .zJ$$$$$P"                        .,;;;!!; <$$$$.  =$
//`$$$$$$$P"     ,ccd$$$$$$$$$"'                         <!!!!!'!! `"?$$h <c$
// $$$$$$$F  .zc???$??""'..`"         zcccc,,,.,..,..   `!!!!'  ' ;!; "$$.`$$
//J$$$$$$$L $P" ,;;,;;!!!''          <$$$$$$$$$$$$P",;,-``!(.-' .<!!!! `$L  "
//$$$$$$$$$ ? ;!!!!!!'``,;;;;;;,      $$$$$"""???" <!'  ' !' ;!!!!!!!!> $$h. 
//$$$$$$$$'  <!!!'  ,;<!!!!!!!!!!>    ?$$$$$c     `!! ,;;!!;<`<!!!!!'`. $$$$.
//$$$$$$$$ ;!!!!'!!!!!!!!!!!!!!!       $$$$$$c     !! !!!!!' ;'`!'' ,$F."???$
//$$$$$$$' `(!!> !!!!!! ..`!!!' ,$     ?$$$$$$.      ;!!!' ;! ., z$$F zJh=y,?
//$$$$$P  ;!!!!> !!!!' <F" `' ,J$$      $$$$$$h     c, `..<'' `,J$$P  " $r`F`
//$$$P" <; ``!!! !!!' .`?chcc$$$L       `$$$$$$c    $$$c,.,ccc$$$$F cc  ".,c$
//.",;<!!!!>; ;! `' z$$L ",$$$$$$c       $$$$$$$c, J$$$$$$??????" z$$$$ ! ?$$
//!!!!!!!!!!! `' c$$$$$$cd$$$$$$$""      $$$$$$$$h $$$$$$$c,.,,zc$$$$$$.`! $$
//!!!!!!!!!!!!!`<$$$$$$$$$$$$$$??        ?$$$$$$$',$$$$$$$$$$$$$$$$$$$$F !><$
//!!!!!!!!!!!!! J$$$$$$$"$$$$$$F         `??$???',$$$$$$$$$$$$$$$$$$$$$ <!> "
//!!!!!!!!!!!' z$$$$$$$$ """??",$$F ,c$,c c  .- ,$$$$$$$$$$$$$$$$$$$$$" !!>  
//!!!!!!!!!',c$$$$$$$$$",$$$$cd$P  J$$$$$$$c=". $$$$$$$$$$$$$$$$$$$$$" !!!>';
//!!!!!!'`,c$$$$$$$$$$$ $$$$$$$F J $$$$$$$"  "F<$$$$$$$$$$$$$$$$$$$$" <!!! <!
//!!!'.,c$$$$$$$$$$$$$$$$$$$$$P J z$$$$P".z$$cc,,.""?$$$$$$$$$$$$$$P >'!!  ``
//! ,J$$$$"".,... "$$$$$$$$$$P / z$$$$P c$$$$$$$$$$$c,."???$$$$$$$" <'`!!! !;
//! ?$$$F ;!!!!!!!  `"??$$$$F `,J$$$$$   `"?$$$$$$$$$$$$hcc ?$$$$" !! `!!! !!
//! <$$" <!!!!!!'.zc,`'-.,..- z$$$$$$'        ""???$$$$$$$$F`??" ;!!! <!!! !!
//!> $" !!!',,,zc$$$$$cc,_' ,J$$$$$$F        <!>;;;;,  $$$$$  ;!!!!!! !!!';!!
//!! ' !!! J$$$$$$$$$$$$$$$$$$$$$$$".         !!!!!!!!;`$$$$h `!!!!!  <!! <!!
//`' .<!! .""???$$$$$$$$$$$$$$$$$$F !          `!!!!!!!;`$$$$$ <!!!! ;,.,;!!!
//Mx`<!'! !!!;;;,."""?$$$$$$$$$$P";!!           <!!!!!!!; $$$$c`!!! , `````.,
//MMn ',`!!!!!!!!!!!>;,,,."""??" <!!             !!!!!!!!; ?$$$.`!>4MMMMMM MM
//MMMb.`,`!!!!!!!!!!!!!!!!!!! ;!!!!              `!!!!!!!!; ?$$$ ' ,_""4MMMMM
//MMMMMx`,`!!!!!!!!!!!!!!!!!' !!!                 !!!!!!!!!> ?$$F MMMMM,  ..`
//
//                                D E G A S
//                       2D/3D Graphics Device Manager
//
//                      Microsoft Windows 95/NT Version
//
//               Copyright (c) 1998 by Charybdis Enterprises, Inc.
//                           All Rights Reserved.
//
//ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
//
//           *** Charybdis Enterprises, Inc. Company Confidential ***
//
//  This file and all associated files are the company proprietary property
//        of Charybdis Enterprises, Inc.  Unauthorized use prohibited.
//
// CHARYBDIS ENTERPRISES, INC. MAKES NO WARRANTIES, EXPRESS OR IMPLIED, AS
// TO THE CORRECTNESS OF THIS CODE OR ANY DERIVATIVE WORKS WHICH INCORPORATE
// IT.  CHARYBDIS ENTERPRISES, INC. PROVIDES THE CODE ON AN "AS-IS" BASIS
// AND EXPLICITLY DISCLAIMS ANY LIABILITY, INCLUDING CONSEQUENTIAL AND
// INCIDENTAL DAMAGES FOR ERRORS, OMISSIONS, AND OTHER PROBLEMS IN THE CODE.
//
//ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
//
// Created by Chuck Walbourn
//
// dgdefs.h
//
// Contains the constants and enumerations for the Degas graphics
// device manager.
//
//อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ

#ifndef __DGDEFS_H
#define __DGDEFS_H  1

#ifdef __WATCOMC__
#pragma pack(1);
#endif

#ifdef _MSC_VER
#pragma pack(push,1)
#endif

//ฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐ
//
//                                Equates
//
//ฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐ

//ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
// Error codes
//ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
typedef enum _dg_error_codes
{
    DG_ERR_NONE             =0x00,
    DG_ERR_INVALIDPARMS     =0x01,
    DG_ERR_NOMEMORY         =0x02,
    DG_ERR_NOTSUPPORTED     =0x03,
    DG_ERR_NOTFOUND         =0x04,
    DG_ERR_INTERNAL         =0x05,

    DG_ERR_ALREADY_OPEN     =0x10,
    DG_ERR_HWINITFAIL       =0x11,
} dg_error_codes;

#ifdef __WATCOMC__
#pragma pack();
#endif

#ifdef _MSC_VER
#pragma pack(pop)
#endif

#endif

//ฐฑฒ End of header - dgdefs.h ฒฑฐ

