MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen VANGOGH
RegisterOpen VANGOGH\INC
RegisterOpen VANGOGH\OBJ
RegisterCurrent VANGOGH\OBJ\MAKEFILE
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\VANGOGH
FilerOpen e:\CHARYBDS\MYTHOS95\VANGOGH\16BPP
FilerOpen e:\CHARYBDS\MYTHOS95\VANGOGH\8BPP
FilerOpen e:\CHARYBDS\MYTHOS95\VANGOGH\INC
FilerCurrent e:\CHARYBDS\MYTHOS95\VANGOGH\8BPP\AZLTT8.CPP
