MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen VANGOGH
RegisterCurrent VANGOGH\VNGITRNS.ASM
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\VANGOGH
FilerCurrent e:\CHARYBDS\MYTHOS95\VANGOGH\VANGOGH.RTF
