MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen VANGOGH
RegisterOpen VANGOGH\INC
RegisterOpen VANGOGH\OBJ
RegisterOpen VANGOGH\TEST
RegisterOpen VANGOGH\TEST\HELP
RegisterOpen VANGOGH\TEST\INC
RegisterOpen VANGOGH\TEST\OBJ
RegisterOpen VANGOGH\UTIL
RegisterCurrent VANGOGH\README.TXT
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\VANGOGH
FilerOpen e:\CHARYBDS\MYTHOS95\VANGOGH\INC
FilerCurrent e:\CHARYBDS\MYTHOS95\VANGOGH\INC\VANGOGH.HPP
