MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen ESCHER
RegisterOpen ESCHER\UTIL
RegisterOpen ESCHER\UTIL\OBJ
RegisterCurrent ESCHER\UTIL\ESHTERR.CPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\UTIL
FilerCurrent e:\CHARYBDS\MYTHOS95\ESCHER\UTIL\ESCHERUG.SAM
