//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
// MaxC -- Event and Trigger Definition System                              ³
// (C) 1994-1999 by D. Higdon, T. Little, and C. Walbourn                   ³
//                                                                          ³
// Event Constants header file for C++                                      ³
//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
#define DONE MaxEvent (0)
#define SELECT_3X6 MaxEvent (1)
#define SELECT_5X8 MaxEvent (2)
#define SELECT_7X12 MaxEvent (3)
#define SELECT_8X13 MaxEvent (4)
#define SELECT_9X15 MaxEvent (5)
#define SELECT_12X24 MaxEvent (6)
#define PAGEUP MaxEvent (7)
#define PAGEDN MaxEvent (8)
// EOF
