//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
// MaxC -- Event and Trigger Definition System                              ³
// (C) 1995 by Charybdis Enterprises, Inc.  All Rights Reserved.            ³
//                                                                          ³
// Event Constants header file for C++                                      ³
//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
const MaxEvent DONE(0);
const MaxEvent SELECT_3X6(1);
const MaxEvent SELECT_5X8(2);
const MaxEvent SELECT_7X12(3);
const MaxEvent SELECT_8X13(4);
const MaxEvent SELECT_9X15(5);
const MaxEvent SELECT_12X24(6);
const MaxEvent PAGEUP(7);
const MaxEvent PAGEDN(8);
// EOF
