MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen GUTENBRG
RegisterOpen GUTENBRG\TEST
RegisterCurrent GUTENBRG\TEST\GLOBAL.HPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG\TEST
FilerCurrent e:\CHARYBDS\MYTHOS95\GUTENBRG\TEST\MAIN.CPP
