MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen VANGOGH
RegisterOpen VANGOGH\TEST
RegisterCurrent VANGOGH\TEST\DEFAULT.PAL
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\VANGOGH
FilerOpen e:\CHARYBDS\MYTHOS95\VANGOGH\TEST
FilerCurrent e:\CHARYBDS\MYTHOS95\VANGOGH\TEST
