MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen ESCHER
RegisterOpen ESCHER\TOOL
RegisterCurrent ESCHER\TOOL\RESOURCE.H
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\TOOL
FilerOpen e:\CHARYBDS\MYTHOS95\ESCHER\TOOL\RES
FilerCurrent e:\CHARYBDS\MYTHOS95\ESCHER\TOOL\ESHTDOC.H
