//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by eshtool.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ESCHERTYPE                  129
#define IDR_ICON_LIGHT                  132
#define IDR_ICON_CAMERA                 134
#define IDR_ICON_MESH                   135
#define IDR_ICON_CAMERAS                136
#define IDR_ICON_LIGHTS                 137
#define IDR_ICON_MESHS                  138
#define IDB_ABOUT                       138
#define IDR_ICON_SCENE                  139
#define IDB_LOGO                        139
#define IDD_CAMPROP_GEN                 140
#define IDR_ICON_SCENES                 140
#define IDD_CAMPROP_MISC                141
#define IDD_CAMPROP_APPFLAGS            142
#define IDD_LGTPROP_GEN                 143
#define IDD_LGTPROP_APPFLAGS            144
#define IDD_MSHPROP_GEN                 145
#define IDD_MSHPROP_APPFLAGS            146
#define IDD_MSHPROP_EXT                 147
#define IDD_MSHPROP_ORIENT              148
#define IDD_SNPROP_GEN                  149
#define IDD_SNPROP_MISC                 150
#define IDD_LGTPROP_EXTRA               151
#define IDD_CAMPROP_EX                  152
#define IDD_MSHPROP_TXTS                153
#define IDD_TXTPROP_GEN                 154
#define IDD_TXTPROP_APPFLAGS            155
#define IDD_MSHPROP_VERTS               156
#define IDD_MSHPROP_FACE                157
#define IDD_FPROP_GEN                   158
#define IDD_FPROP_APPFLAGS              159
#define IDD_FPROP_FLAGS                 160
#define IDC_LPROP_NAME                  1001
#define IDC_LPROP_TYPE                  1002
#define IDC_LPROP_INTENSITY             1004
#define IDC_LPROP_XI                    1005
#define IDC_LPROP_YJ                    1006
#define IDC_CPROP_FLAGS_APP1            1007
#define IDC_LPROP_ZK                    1007
#define IDC_CPROP_FLAGS_APP2            1008
#define IDC_LPROP_ON                    1008
#define IDC_SPROP_DESC                  1008
#define IDC_CPROP_FLAGS_APP3            1009
#define IDC_SPROP_AUTH                  1009
#define IDC_LPROP_ATTEN                 1009
#define IDC_CPROP_FLAGS_APP4            1010
#define IDC_MPROP_CHKEXT                1010
#define IDC_SPROP_COPY                  1010
#define IDC_LPROP_DARK                  1010
#define IDC_LPROP_FLAGS_APP1            1011
#define IDC_MPROP_FLAGS_APP9            1011
#define IDC_LPROP_FLAGS_APP2            1012
#define IDC_MPROP_FLAGS_APPA            1012
#define IDC_LPROP_FLAGS_APP3            1013
#define IDC_MPROP_FLAGS_APPB            1013
#define IDC_LPROP_FLAGS_APP4            1014
#define IDC_MPROP_FLAGS_APPC            1014
#define IDC_CPROP_FLAGS_APP5            1015
#define IDC_CPROP_FLAGS_APP6            1016
#define IDC_CPROP_FLAGS_APP7            1017
#define IDC_CPROP_FLAGS_APP0            1018
#define IDC_LPROP_FLAGS_APP5            1019
#define IDC_MPROP_FLAGS_APPE            1019
#define IDC_LPROP_FLAGS_APP6            1020
#define IDC_MPROP_FLAGS_APPF            1020
#define IDC_LPROP_FLAGS_APP7            1021
#define IDC_CPROP_XPOS                  1022
#define IDC_LPROP_FLAGS_APP0            1022
#define IDC_CPROP_BCOLR                 1023
#define IDC_MPROP_NAME                  1023
#define IDC_CPROP_YPOS                  1024
#define IDC_MPROP_PARENT                1024
#define IDC_CPROP_ZPOS                  1025
#define IDC_MPROP_CHILD                 1025
#define IDC_CPROP_YON                   1026
#define IDC_MPROP_XPOS                  1026
#define IDC_CPROP_HITHER                1027
#define IDC_MPROP_YPOS                  1027
#define IDC_CPROP_FOV                   1028
#define IDC_CPROP_SCALEF                1028
#define IDC_MPROP_ZPOS                  1028
#define IDC_CPROP_NAME                  1029
#define IDC_MPROP_FLAGS_APP0            1029
#define IDC_MPROP_MTXD                  1029
#define IDC_ABOUT_VERSION               1030
#define IDC_CPROP_ITOP                  1030
#define IDC_MPROP_FLAGS_APP8            1030
#define IDC_MPROP_MTXE                  1030
#define IDC_MPROP_NFACES                1030
#define IDC_CPROP_JTOP                  1031
#define IDC_MPROP_FLAGS_APPD            1031
#define IDC_MPROP_MTXF                  1031
#define IDC_MPROP_NVERTS                1031
#define IDC_CPROP_KTOP                  1032
#define IDC_MPROP_FLAGS_APP1            1032
#define IDC_CPROP_IDIR                  1033
#define IDC_MPROP_FLAGS_APP2            1033
#define IDC_CPROP_JDIR                  1034
#define IDC_MPROP_FLAGS_APP3            1034
#define IDC_CPROP_KDIR                  1035
#define IDC_MPROP_FLAGS_APP4            1035
#define IDC_MPROP_MTXG                  1035
#define IDC_MPROP_FLAGS_APP5            1036
#define IDC_MPROP_MTXH                  1036
#define IDC_CPROP_WIDTH                 1036
#define IDC_MPROP_FLAGS_APP6            1037
#define IDC_MPROP_MTXI                  1037
#define IDC_CPROP_HEIGHT                1037
#define IDC_MPROP_FLAGS_APP7            1038
#define IDC_MPROP_XCEN                  1039
#define IDC_MPROP_YCEN                  1040
#define IDC_MPROP_ZCEN                  1041
#define IDC_MPROP_RADIUS                1042
#define IDC_MPROP_MTXA                  1042
#define IDC_MPROP_MTXB                  1043
#define IDC_MPROP_XMIN                  1044
#define IDC_MPROP_MTXC                  1044
#define IDC_MPROP_YMIN                  1045
#define IDC_MPROP_VISIBLE               1045
#define IDC_MPROP_ZMIN                  1046
#define IDC_SPROP_NAME                  1046
#define IDC_MPROP_XMAX                  1047
#define IDC_SPROP_NCAMERAS              1047
#define IDC_LPROP_INNER                 1047
#define IDC_MPROP_YMAX                  1048
#define IDC_SPROP_NMESHES               1048
#define IDC_LPROP_OUTER                 1048
#define IDC_CPROP_HCOLR                 1048
#define IDC_MPROP_ZMAX                  1049
#define IDC_SPROP_NVLIGHTS              1049
#define IDC_CPROP_BMBACK                1049
#define IDC_SPROP_NPLIGHTS              1050
#define IDC_LPROP_HOTSPOT               1050
#define IDC_SPROP_NFPLIGHTS             1051
#define IDC_LPROP_FALLOFF               1051
#define IDC_CPROP_BITMAP                1051
#define IDC_SPROP_NALIGHTS              1052
#define IDC_CPROP_HAZE                  1052
#define IDC_SPROP_NSLIGHTS              1053
#define IDC_SPROP_NFALIGHTS             1054
#define IDC_CPROP_LEVEL                 1054
#define IDC_CPROP_STARTZ                1054
#define IDC_SPROP_NFSLIGHTS             1055
#define IDC_CPROP_BLEVEL                1055
#define IDC_CPROP_SLEVEL                1056
#define IDC_MPROP_TXTLIST               1056
#define IDC_CPROP_MIDZ                  1056
#define IDC_CPROP_BPERC                 1057
#define IDC_MPROP_TXTPROP               1057
#define IDC_TPROP_NAME                  1058
#define IDC_TPROP_TYPE                  1059
#define IDC_TPROP_ANIMATE               1060
#define IDC_TPROP_WIDTH                 1061
#define IDC_TPROP_HEIGHT                1062
#define IDC_MPROP_VLIST                 1062
#define IDC_TPROP_NFRAMES               1063
#define IDC_MPROP_FLIST                 1063
#define IDC_MPROP_FPROP                 1064
#define IDC_FPROP_A                     1065
#define IDC_FPROP_B                     1066
#define IDC_FPROP_C                     1067
#define IDC_FPROP_TXT                   1068
#define IDC_FPROP_U0                    1069
#define IDC_FPROP_FLAGS_APP0            1069
#define IDC_FPROP_V0                    1070
#define IDC_FPROP_FLAGS_APP1            1070
#define IDC_FPROP_U1                    1071
#define IDC_FPROP_FLAGS_APP2            1071
#define IDC_FPROP_V1                    1072
#define IDC_FPROP_FLAGS_APP3            1072
#define IDC_FPROP_U2                    1073
#define IDC_FPROP_WIRE                  1073
#define IDC_FPROP_V2                    1074
#define IDC_FPROP_SOLID                 1074
#define IDC_FPROP_I                     1075
#define IDC_FPROP_FLAT                  1075
#define IDC_FPROP_J                     1076
#define IDC_FPROP_SMOOTH                1076
#define IDC_FPROP_K                     1077
#define IDC_FPROP_SPECULAR              1077
#define IDC_FPROP_1SIDED                1078
#define IDC_FPROP_APERSP                1079
#define IDC_FPROP_SELFILLM              1080
#define IDC_FPROP_ABLINE                1081
#define IDC_FPROP_BCLINE                1082
#define IDC_FPROP_CALINE                1083
#define IDC_FPROP_ALPHA                 1084
#define IDC_FPROP_SELFILLUM             1085
#define IDC_FPROP_ALPHAA                1086
#define IDC_FPROP_ALPHAB                1087
#define IDC_FPROP_ALPHAC                1088
#define ID_FILE_PALETTE                 32772
#define ID_EDIT_PROP                    32774
#define ID_VIEW_RND_ALL_LINES           32775
#define ID_EDIT_DELETE                  32776
#define ID_MESH_ROTIJ                   32777
#define ID_MESH_MOVEIJ                  32778
#define ID_MESH_ROTMOVEK                32779
#define ID_VIEW_ATTACHCAM               32780
#define ID_EDIT_NEW_CAM                 32783
#define ID_EDIT_NEW_LIGHT               32784
#define ID_FILE_IMPORT                  32785
#define ID_APP_HELP                     32787
#define ID_VIEW_AUTOROTX                32789
#define ID_VIEW_AUTOROTZ                32791
#define ID_VIEW_AUTOROTY                32792
#define ID_VIEW_AUTOFAST                32793
#define ID_VIEW_AUTOSLOW                32794
#define ID_VIEW_AUTOOFF                 32795
#define ID_VIEW_RND_MSPACE              32796
#define ID_VIEW_SHOW_SPHEXTS            32797
#define ID_VIEW_SHOW_BOXEXTS            32798
#define ID_FILE_COMPRESS                32799
#define ID_FILE_TRUECOLOR               32800
#define ID_FILE_FLOATING                32801
#define ID_VIEW_RND_SORT                32802
#define ID_VIEW_RND_ALPHA               32803
#define ID_VIEW_RND_ORTHO               32804
#define ID_VIEW_REFRESH                 32809
#define ID_VIEW_RND_SPECULAR            32816
#define ID_VIEW_RND_WIREFRAME           32820
#define ID_VIEW_RND_FLAT                32821
#define ID_VIEW_RND_SMOOTH              32822
#define ID_VIEW_RND_BACKFACE            32824
#define ID_VIEW_RND_TEXTURES            32825
#define ID_VIEW_RND_SOLID               32826
#define ID_VIEW_RND_PERSPECTIVE         32827
#define ID_VIEW_ROTXY                   32828
#define ID_VIEW_MOVEXY                  32829
#define ID_VIEW_ROTMOVEZ                32831
#define ID_LGT_ADJUSTXY                 32833
#define ID_LGT_ABRIGHT                  32835
#define ID_STATIC                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
