MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen MAX
RegisterOpen MAX\INC
RegisterCurrent MAX
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\MAX
FilerOpen e:\CHARYBDS\MYTHOS95\MAX\INC
FilerOpen e:\CHARYBDS\MYTHOS95\MAX\OBJ
FilerCurrent e:\CHARYBDS\MYTHOS95\MAX\INC\MAXVMAP.HPP
