MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen SIMGINE
RegisterOpen SIMGINE\TEST
RegisterCurrent SIMGINE\TEST\STSTATE.CPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\SIMGINE
FilerOpen e:\CHARYBDS\MYTHOS95\SIMGINE\TEST
FilerCurrent e:\CHARYBDS\MYTHOS95\SIMGINE\TEST\ST.BAT
