MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen CHRONOS
RegisterOpen CHRONOS\INC
RegisterOpen CHRONOS\OBJ
RegisterOpen CHRONOS\TEST
RegisterOpen CHRONOS\TEST\OBJ
RegisterCurrent CHRONOS\README.TXT
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\CHRONOS
FilerCurrent e:\CHARYBDS\MYTHOS95\CHRONOS
