MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen GUTENBRG
RegisterOpen GUTENBRG\INC
RegisterOpen GUTENBRG\OBJ
RegisterOpen GUTENBRG\TEST
RegisterOpen GUTENBRG\TEST\OBJ
RegisterOpen GUTENBRG\UTIL
RegisterOpen GUTENBRG\UTIL\OBJ
RegisterCurrent GUTENBRG\README.TXT
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG\INC
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG\OBJ
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG\TEST
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG\TEST\OBJ
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG\UTIL
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG\UTIL\OBJ
FilerCurrent e:\CHARYBDS\MYTHOS95\GUTENBRG\README.TXT
