MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen GUTENBRG
RegisterCurrent GUTENBRG\GBRGOUTC.CPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\GUTENBRG
FilerCurrent e:\CHARYBDS\MYTHOS95\GUTENBRG\GBRGXFNT.CPP
