MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen XFILE
RegisterOpen XFILE\OBJ
RegisterOpen XFILE\UTIL
RegisterCurrent XFILE\UTIL\XUIFFDIR.CPP
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\XFILE
FilerOpen e:\CHARYBDS\MYTHOS95\XFILE\UTIL
FilerCurrent e:\CHARYBDS\MYTHOS95\XFILE\UTIL\MK.BAT
