//อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ
//                            
//           ^           **   **   **** ***** *    ****     ^      Take me to
//          (_)            * *     *      *   *    *       (_)    / your
//     ^                    *      **     *   *    **            ^  leader...
//    (_)       ^          * *     *      *   *    *            (_)
//             (_)       **   **   *    ***** **** ****
//
//            Copyright (c) 1994,1995 by Charybdis Enterprises, Inc.
//                              All Rights Reserved.
//                        Microsoft Windows '95 Version
//
//ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
//
//           *** Charybdis Enterprises, Inc. Company Confidential ***
//
//  This file and all associated files are the company proprietary property
//        of Charybdis Enterprises, Inc.  Unauthorized use prohibited.
//
// CHARYBDIS ENTERPRISES, INC. MAKES NO WARRANTIES, EXPRESS OR IMPLIED, AS
// TO THE CORRECTNESS OF THIS CODE OR ANY DERIVATIVE WORKS WHICH INCORPORATE
// IT.  CHARYBDIS ENTERPRISES, INC. PROVIDES THE CODE ON AN "AS-IS" BASIS
// AND EXPLICITLY DISCLAIMS ANY LIABILITY, INCLUDING CONSEQUENTIAL AND
// INCIDENTAL DAMAGES FOR ERRORS, OMISSIONS, AND OTHER PROBLEMS IN THE CODE.
//
//ฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤฤ
//
//                              *** Utilities ***
//
// Created by Chuck Walbourn
// 
// xuifftok.h
//
//     Token header for IFF Compiler
//
//อออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออออ

#ifndef __XUIFFTOK_H
#define __XUIFFTOK_H    1

//ฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐ
//
//                                Equates
//
//ฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐฐ

#define YY_LBRACKET            1
#define YY_RBRACKET            2
#define YY_LPAREN              3
#define YY_RPAREN              4
#define YY_LBRACE              5
#define YY_RBRACE              6
#define YY_PLUS                7
#define YY_MINUS               8
#define YY_MULTIPLY            9
#define YY_DIVIDE              10
#define YY_COMMA               11

#define YY_INCLUDE             100
#define YY_FORM                101
#define YY_CHUNK               102
#define YY_MERGE               103
#define YY_INTEL               104
#define YY_BIGENDIAN           105
#define YY_MOTOROLA            106
#define YY_LITTLEENDIAN        107
#define YY_SIZE                108
#define YY_BYTE                109
#define YY_UBYTE               110
#define YY_WORD                111
#define YY_UWORD               112
#define YY_LONG                113
#define YY_ULONG               114
#define YY_DWORD               115
#define YY_UDWORD              116
#define YY_TEXT                117
#define YY_BINARY              118
#define YY_FLOAT               119
#define YY_DOUBLE              120
#define YY_FIXED16             121

#define YY_INTEGER             200
#define YY_REAL                201
#define YY_STRING              202

#endif

//ฐฑฒ End of header - xuifftok.h ฒฑฐ

