MakeBackups 1
FileLocks 1
ShowDeleted 1
RegisterOpen XFILE
RegisterCurrent XFILE\XFILE.RTF
FilerOpen e:
FilerOpen e:\CHARYBDS
FilerOpen e:\CHARYBDS\MYTHOS95
FilerOpen e:\CHARYBDS\MYTHOS95\XFILE
FilerCurrent e:\CHARYBDS\MYTHOS95\XFILE\XFILE.RTF
