//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
// MaxC -- Event and Trigger Definition System                              ³
// (C) 1995-1997 by Charybdis Enterprises, Inc.  All Rights Reserved.       ³
//                                                                          ³
// Event Constants header file for C++                                      ³
//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
#define ALL_LINES MaxEvent (0)
#define MODEL_SPACE MaxEvent (1)
#define BACKCULL MaxEvent (2)
#define SHADE_WIRE MaxEvent (3)
#define SHADE_SOLID MaxEvent (4)
#define SHADE_FLAT MaxEvent (5)
#define SHADE_SMOOTH MaxEvent (6)
#define SHADE_SPECULAR MaxEvent (7)
#define TEXTURE_MAP MaxEvent (8)
#define BITMAP_BACKGROUND MaxEvent (9)
#define SHADE_PERSPECTIVE MaxEvent (10)
#define ZBUFFER MaxEvent (11)
#define MOVEXY MaxEvent (12)
#define MOVEZ MaxEvent (13)
#define LIGHT_POSITION MaxEvent (14)
#define LIGHT_IN_BRIGHTER MaxEvent (15)
#define LIGHT_IN_DIMMER MaxEvent (16)
#define CAMERA_ROTATE MaxEvent (17)
#define CAMERA_MOVE MaxEvent (18)
#define ALLI MaxEvent (19)
#define ALLJ MaxEvent (20)
#define ALLK MaxEvent (21)
#define OBJECT_ROTATE MaxEvent (22)
#define OBJECT_MOVE MaxEvent (23)
#define OBJECT_NEXT MaxEvent (24)
#define OBJECT_PREV MaxEvent (25)
#define OBJECT_CHILD MaxEvent (26)
#define FASTER MaxEvent (27)
#define SLOWER MaxEvent (28)
#define TERRAIN_DOTS MaxEvent (29)
#define TERRAIN_LOD MaxEvent (30)
#define TERRAIN_DEBUG MaxEvent (31)
#define CAM_HOVER MaxEvent (32)
#define ADJUST_ALPHA MaxEvent (33)
#define ADJUST_FOV MaxEvent (34)
#define ADJUST_FACTOR MaxEvent (35)
#define ADJUST_MBOX_SIZE MaxEvent (36)
#define ADJUST_BM_OFFSET MaxEvent (37)
#define SHOW_EXTENTS MaxEvent (38)
#define HAZING MaxEvent (39)
#define GRADIENT MaxEvent (40)
#define FIRE_INCREASE MaxEvent (41)
#define FIRE_DECREASE MaxEvent (42)
#define FIRE_DOUSE MaxEvent (43)
#define FIRE_FIREBALL MaxEvent (44)
#define SHOW_FPS MaxEvent (45)
#define PARTN_TOGGLE MaxEvent (46)
#define EXPLOSION_RESET MaxEvent (47)
#define DONE MaxEvent (48)
#define UP MaxEvent (49)
#define DOWN MaxEvent (50)
#define LEFT MaxEvent (51)
#define RIGHT MaxEvent (52)
#define PARTN_LIST MaxEvent (53)
// EOF
