//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
// MaxC -- Event and Trigger Definition System                              ³
// (C) 1995-1997 by Charybdis Enterprises, Inc.  All Rights Reserved.       ³
//                                                                          ³
// Event Constants header file for C++                                      ³
//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
#define ALL_LINES MaxEvent (0)
#define MODEL_SPACE MaxEvent (1)
#define BACKCULL MaxEvent (2)
#define SHADE_WIRE MaxEvent (3)
#define SHADE_SOLID MaxEvent (4)
#define SHADE_FLAT MaxEvent (5)
#define SHADE_SMOOTH MaxEvent (6)
#define SHADE_SPECULAR MaxEvent (7)
#define TEXTURE_MAP MaxEvent (8)
#define BITMAP_BACKGROUND MaxEvent (9)
#define SHADE_PERSPECTIVE MaxEvent (10)
#define SHADE_ALPHA MaxEvent (11)
#define SORT MaxEvent (12)
#define ZBUFFER MaxEvent (13)
#define MOVEXY MaxEvent (14)
#define MOVEZ MaxEvent (15)
#define LIGHT_POSITION MaxEvent (16)
#define LIGHT_IN_BRIGHTER MaxEvent (17)
#define LIGHT_IN_DIMMER MaxEvent (18)
#define CAMERA_ROTATE MaxEvent (19)
#define CAMERA_MOVE MaxEvent (20)
#define ALLI MaxEvent (21)
#define ALLJ MaxEvent (22)
#define ALLK MaxEvent (23)
#define OBJECT_ROTATE MaxEvent (24)
#define OBJECT_MOVE MaxEvent (25)
#define OBJECT_NEXT MaxEvent (26)
#define OBJECT_PREV MaxEvent (27)
#define OBJECT_CHILD MaxEvent (28)
#define FASTER MaxEvent (29)
#define SLOWER MaxEvent (30)
#define TERRAIN_DOTS MaxEvent (31)
#define TERRAIN_LOD MaxEvent (32)
#define TERRAIN_DEBUG MaxEvent (33)
#define CAM_HOVER MaxEvent (34)
#define ADJUST_ALPHA MaxEvent (35)
#define ADJUST_FOV MaxEvent (36)
#define ADJUST_FACTOR MaxEvent (37)
#define ADJUST_MBOX_SIZE MaxEvent (38)
#define ADJUST_BM_OFFSET MaxEvent (39)
#define SHOW_EXTENTS MaxEvent (40)
#define HAZING MaxEvent (41)
#define GRADIENT MaxEvent (42)
#define FIRE_INCREASE MaxEvent (43)
#define FIRE_DECREASE MaxEvent (44)
#define FIRE_DOUSE MaxEvent (45)
#define FIRE_FIREBALL MaxEvent (46)
#define SHOW_FPS MaxEvent (47)
#define PARTN_TOGGLE MaxEvent (48)
#define EXPLOSION_RESET MaxEvent (49)
#define DONE MaxEvent (50)
#define UP MaxEvent (51)
#define DOWN MaxEvent (52)
#define LEFT MaxEvent (53)
#define RIGHT MaxEvent (54)
#define PARTN_LIST MaxEvent (55)
// EOF
