//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ¿
// MaxC -- Event and Trigger Definition System                              ³
// (C) 1995-1997 by Charybdis Enterprises, Inc.  All Rights Reserved.       ³
//                                                                          ³
// Event Constants header file for C++                                      ³
//ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ
#define ALL_LINES MaxEvent (0)
#define MODEL_SPACE MaxEvent (1)
#define BACKCULL MaxEvent (2)
#define SHADE_WIRE MaxEvent (3)
#define SHADE_SOLID MaxEvent (4)
#define SHADE_FLAT MaxEvent (5)
#define SHADE_FLAT_SPECULAR MaxEvent (6)
#define SHADE_SMOOTH MaxEvent (7)
#define SHADE_SPECULAR MaxEvent (8)
#define TEXTURE_MAP MaxEvent (9)
#define BITMAP_BACKGROUND MaxEvent (10)
#define SHADE_PERSPECTIVE MaxEvent (11)
#define SHADE_ALPHA MaxEvent (12)
#define SORT MaxEvent (13)
#define ZBUFFER MaxEvent (14)
#define MOVEXY MaxEvent (15)
#define MOVEZ MaxEvent (16)
#define LIGHT_POSITION MaxEvent (17)
#define LIGHT_IN_BRIGHTER MaxEvent (18)
#define LIGHT_IN_DIMMER MaxEvent (19)
#define CAMERA_ROTATE MaxEvent (20)
#define CAMERA_MOVE MaxEvent (21)
#define ALLI MaxEvent (22)
#define ALLJ MaxEvent (23)
#define ALLK MaxEvent (24)
#define OBJECT_ROTATE MaxEvent (25)
#define OBJECT_MOVE MaxEvent (26)
#define OBJECT_NEXT MaxEvent (27)
#define OBJECT_PREV MaxEvent (28)
#define OBJECT_CHILD MaxEvent (29)
#define FASTER MaxEvent (30)
#define SLOWER MaxEvent (31)
#define TERRAIN_DOTS MaxEvent (32)
#define TERRAIN_LOD MaxEvent (33)
#define TERRAIN_DEBUG MaxEvent (34)
#define CAM_HOVER MaxEvent (35)
#define ADJUST_ALPHA MaxEvent (36)
#define ADJUST_FOV MaxEvent (37)
#define ADJUST_FACTOR MaxEvent (38)
#define ADJUST_MBOX_SIZE MaxEvent (39)
#define ADJUST_BM_OFFSET MaxEvent (40)
#define SHOW_EXTENTS MaxEvent (41)
#define SHOW_PARTN MaxEvent (42)
#define HAZING MaxEvent (43)
#define GRADIENT MaxEvent (44)
#define FIRE_INCREASE MaxEvent (45)
#define FIRE_DECREASE MaxEvent (46)
#define FIRE_DOUSE MaxEvent (47)
#define FIRE_FIREBALL MaxEvent (48)
#define SHOW_FPS MaxEvent (49)
#define PARTN_TOGGLE MaxEvent (50)
#define EXPLOSION_RESET MaxEvent (51)
#define DONE MaxEvent (52)
#define UP MaxEvent (53)
#define DOWN MaxEvent (54)
#define LEFT MaxEvent (55)
#define RIGHT MaxEvent (56)
#define PARTN_LIST MaxEvent (57)
// EOF
